name = "safebox-api"
type = "javascript"
kv_namespaces = [
  { binding = "MESSAGES", preview_id = "49eb9438c3a940278439bc9d0dfd5e85", id = "db1f20a3251a4efe9d95acfc2bf85656" }
]
zone_id = "da5e767f499758c8f050b3f4decfe23a"
workers_dev = false
# route = "*safebox.dev/api/*"
compatibility_date = "2021-10-22"

[build]
command = "npm run build"

[build.upload]
dir = "durable_objects"
format = "modules"
main = "sync.mjs"

[durable_objects]
bindings = [
  { name = "SYNCS", class_name = "Sync" }
]

[miniflare]
kv_persist = true
durable_objects_persist = true